name: GET UP

on:
  workflow_dispatch:

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --all-groups

      - name: GET UP
        run: |
          uv run get-up ${{ secrets.G_T }} ${{ github.repository }} --tele_token ${{ secrets.TG_TOKEN }} --tele_chat_id ${{ secrets.TG_CHAT_ID }}

      - name: Push New Pic
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "generated today pic" || echo "no need to commit "
          git push || echo "no file change"
