name: GET UP

on:
  workflow_dispatch:
    inputs:
      message:
        description: "weather message"
        required: false

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chinese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig fonts-noto-cjk
          fc-cache -fv

      - name: GET UP
        run: |
          python get_up.py ${{ secrets.G_T }} ${{ github.repository }}  --weather_message ": ${{ github.event.inputs.message }}" --tele_token ${{ secrets.TG_TOKEN }} --tele_chat_id ${{ secrets.TG_CHAT_ID }}

      - name: Push New Pic
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add blog_sites_used.txt cities_used.txt leetcode_used.txt leetcode_hot100_used.txt city_posters
          git commit -m "generated today pic" || echo "no need to commit "
          git push || echo "no file change"
